template = "https://github.com/giellalt/template-lang-und"
rev_id = 271
template_sha = "58889500fa56906fc67098b753f74968988220af"

[replacements]
__GLOTTOLOG_ID__ = "faro1244"
__REPO__ = "lang-fao"
__UND2C__ = "fo"
__UNDEFINED__ = "Faroese"
__UND__ = "fao"
