---
name: Docs
on:
  push:
    branches:
      - 'main'
jobs:
  build-and-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          repository: giellalt/giella-core
          path: giella-core
      - uses: actions/checkout@v4
        with:
          repository: giellalt/giella-shared
          path: giella-shared
      - uses: actions/checkout@v4
        with:
          path: lang
      - name: Install dev dependencies
        uses: divvun/actions/lang/install-deps@master
        with:
          sudo: true
      - name: Build giella-core/giella-shared
        uses: divvun/actions/lang/build@master
        with:
          spellers: false
          fst: hfst

      # Mermaid processing starts here:
      - name: get list of files
        id: getfile
        run: |
          echo "::set-output name=files::$(find lang/docs -name '*.md' | xargs)"

      - name: print list of files for debugging
        run: |
          echo ${{ steps.getfile.outputs.files }}

      # The actual Mermaid compilation
      - name: compile mermaid
        uses: divvun/compile-mermaid-markdown-action@main
        with:
          files: ${{ steps.getfile.outputs.files }}
          output: 'lang/docs/mermaid-svgs'
        env:
          HIDE_CODEBLOCKS: 1
          # The next one must be declared, with an empty value, for paths to work for us:
          ABSOLUTE_IMAGE_LINKS:
          OUTPUT_FILE_TYPE: "svg"

      - name: list generated svg fils
        run: |
          cd lang && ls -l docs/mermaid-svgs
      # Mermaid processing ends here

      - name: deploy gh pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: lang/docs/
          enable_jekyll: true
